version: "2"
services:
  redis:
    image: redislabs/redisearch:1.6.13
    ports:
      - "6379"

  backend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000"
    links:
      - redis:redis
    volumes:
      - /var/lib/flatpak
